# Navigate in a grid

Each cell has a given cost, the robot can start from any cell of the top row and must reach the bottom row by taking the path minimizing the overall cost.

At each step the robot can only go straight down, or down in diagonal

In [ ]:
import numpy as np


def solve(grid: np.ndarray[int]):
    n, m = grid.shape
    cost_to_go = grid.copy()
    path = [[-1]*n for _ in range(m)]
    for i in range(m):
        path[i][0] = i # start the path at index i

    for row_id in range(n-2, -1, -1):
        for col_id in range(m):

            min_col = max(0, col_id-1)
            max_col = min(m, col_id+2)
            next_id = min_col + np.argmin(cost_to_go[row_id+1, min_col:max_col])

            # cost = current step cost + minimum of the next 3 possibilities
            cost_to_go[row_id, col_id] = grid[row_id, col_id] + cost_to_go[row_id+1, next_id]
            path[col_id][row_id+1] = next_id

    print(cost_to_go)
    print(path)
    start_id = np.argmin(cost_to_go[0])
    lowest_cost = cost_to_go[0, start_id]
    best_path = path[start_id]

    return lowest_cost, best_path

In [7]:
grid = np.array([[1, 4, 3, 4, 2],
                 [4, 7, 1, 5, 3],
                 [7, 2, 6, 4, 1]])

lowest_cost, best_path = solve(grid)
print(lowest_cost, best_path)

[[7 7 6 7 6]
 [6 9 3 6 4]
 [7 2 6 4 1]]
[[0, 0, 1], [1, 2, 1], [2, 2, 1], [3, 2, 4], [4, 4, 4]]
[7 2 6 4 1] [2, 2, 1]
